
version: '3'

services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taina
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
